//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ASDisplayNode.h"

@interface _TtC24AnimatedNativeLottieNodeP33_45C5457DA62AC1EF8218E3E8A905769637AnimatedNativeLottieNodeDisplayEvents : ASDisplayNode
{
    // Error parsing type: , name: value
    // Error parsing type: , name: updated
}

- (void).cxx_destruct;
- (void)didExitHierarchy;
- (void)didEnterHierarchy;
- (id)init;

@end

