//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCTEventEmitter.h"

#import "RCTBridgeModule-Protocol.h"
#import "RCTInvalidating-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSObject, NSString, RCTBridge;
@protocol OS_dispatch_queue;

@interface DCDVoiceEngine : RCTEventEmitter <RCTBridgeModule, RCTInvalidating>
{
    NSMutableDictionary *_videoSinks;
    struct map<unsigned long, std::__1::shared_ptr<discord::voice::Connection>, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, std::__1::shared_ptr<discord::voice::Connection>>>> _connections;
    struct map<unsigned long, discord::AudioModeType, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, discord::AudioModeType>>> _connectionInputModes;
    struct shared_ptr<Discord> _discord;
    _Bool _keepAlive;
    _Bool _discordReady;
    NSMutableArray *_discordDeferredBlocks;
}

+ (const struct RCTMethodInfo *)__rct_export__122834;
+ (const struct RCTMethodInfo *)__rct_export__121733;
+ (const struct RCTMethodInfo *)__rct_export__119732;
+ (const struct RCTMethodInfo *)__rct_export__118831;
+ (const struct RCTMethodInfo *)__rct_export__116830;
+ (const struct RCTMethodInfo *)__rct_export__116429;
+ (const struct RCTMethodInfo *)__rct_export__115328;
+ (const struct RCTMethodInfo *)__rct_export__114227;
+ (const struct RCTMethodInfo *)__rct_export__112926;
+ (const struct RCTMethodInfo *)__rct_export__112225;
+ (const struct RCTMethodInfo *)__rct_export__111224;
+ (const struct RCTMethodInfo *)__rct_export__110223;
+ (const struct RCTMethodInfo *)__rct_export__109122;
+ (const struct RCTMethodInfo *)__rct_export__108221;
+ (const struct RCTMethodInfo *)__rct_export__106120;
+ (const struct RCTMethodInfo *)__rct_export__83219;
+ (const struct RCTMethodInfo *)__rct_export__81918;
+ (const struct RCTMethodInfo *)__rct_export__80417;
+ (const struct RCTMethodInfo *)__rct_export__79016;
+ (const struct RCTMethodInfo *)__rct_export__77615;
+ (const struct RCTMethodInfo *)__rct_export__69714;
+ (const struct RCTMethodInfo *)__rct_export__67313;
+ (const struct RCTMethodInfo *)__rct_export__66212;
+ (const struct RCTMethodInfo *)__rct_export__64611;
+ (const struct RCTMethodInfo *)__rct_export__64110;
+ (const struct RCTMethodInfo *)__rct_export__6279;
+ (const struct RCTMethodInfo *)__rct_export__6158;
+ (const struct RCTMethodInfo *)__rct_export__6017;
+ (const struct RCTMethodInfo *)__rct_export__5896;
+ (const struct RCTMethodInfo *)__rct_export__5755;
+ (const struct RCTMethodInfo *)__rct_export__5634;
+ (const struct RCTMethodInfo *)__rct_export__5443;
+ (const struct RCTMethodInfo *)__rct_export__5372;
+ (const struct RCTMethodInfo *)__rct_export__5301;
+ (const struct RCTMethodInfo *)__rct_export__4750;
+ (map_5554a4ce)getCodecParameters:(id)arg1;
+ (id)convertVideoInputDeviceDescriptions:(const vector_16ee0dc2 *)arg1;
+ (id)convertAudioOutputDeviceDescriptions:(const vector_25fd4b61 *)arg1;
+ (id)convertAudioInputDeviceDescriptions:(const vector_25fd4b61 *)arg1;
+ (_Bool)requiresMainQueueSetup;
+ (void)load;
+ (id)moduleName;
@property(retain, nonatomic) NSMutableArray *discordDeferredBlocks; // @synthesize discordDeferredBlocks=_discordDeferredBlocks;
@property(nonatomic) _Bool discordReady; // @synthesize discordReady=_discordReady;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)connectionInstanceGetFilteredStats:(unsigned long long)arg1 filter:(int)arg2 callback:(CDUnknownBlockType)arg3;
- (void)connectionInstanceSetPingInterval:(unsigned long long)arg1 pingInterval:(int)arg2;
- (void)connectionInstanceGetStats:(unsigned long long)arg1 callback:(CDUnknownBlockType)arg2;
- (void)connectionInstanceSetPTTActive:(unsigned long long)arg1 withActive:(_Bool)arg2 withPriority:(_Bool)arg3;
- (void)connectionInstanceTriggerOnVideoCallback:(unsigned long long)arg1;
- (void)connectionInstanceSetNoInputThreshold:(unsigned long long)arg1 threshold:(float)arg2;
- (void)connectionInstanceSetMinimumOutputDelay:(unsigned long long)arg1 delay:(int)arg2;
- (void)connectionInstanceSetSelfDeafen:(unsigned long long)arg1 deafened:(_Bool)arg2;
- (void)connectionInstanceSetSelfMute:(unsigned long long)arg1 muted:(_Bool)arg2;
- (void)connectionInstanceSetLocalMute:(unsigned long long)arg1 userId:(id)arg2 muted:(_Bool)arg3;
- (void)connectionInstanceSetLocalVolume:(unsigned long long)arg1 userId:(id)arg2 volume:(double)arg3;
- (void)connectionInstanceSetLocalPan:(unsigned long long)arg1 userId:(id)arg2 left:(double)arg3 right:(double)arg4;
- (void)connectionInstanceSetVideoBroadcast:(unsigned long long)arg1 broadcasting:(_Bool)arg2;
- (void)connectionInstanceDestroyUser:(unsigned long long)arg1 userId:(id)arg2;
- (void)connectionInstanceMergeUsers:(unsigned long long)arg1 users:(id)arg2;
- (void)connectionInstanceSetTransportOptions:(unsigned long long)arg1 options:(id)arg2;
- (void)connectionInstanceSetEncodingBitRate:(unsigned long long)arg1 bitRate:(int)arg2;
- (void)connectionInstanceGetEncryptionModes:(unsigned long long)arg1 callback:(CDUnknownBlockType)arg2;
- (void)connectionInstanceConfigureConnectionRetries:(unsigned long long)arg1 baseDelayMs:(int)arg2 maxDelayMs:(int)arg3 maxAttempts:(int)arg4;
- (void)connectionInstanceDestroy:(unsigned long long)arg1;
- (void)createVoiceConnection:(unsigned long long)arg1 withSsrc:(unsigned long long)arg2 userId:(id)arg3 serverIp:(id)arg4 port:(int)arg5 callback:(CDUnknownBlockType)arg6;
- (void)getSupportedVideoCodecs:(CDUnknownBlockType)arg1;
- (void)getAudioSubsystem:(CDUnknownBlockType)arg1;
- (void)setAVAudioSessionMode:(id)arg1;
- (void)setNoInputThreshold:(float)arg1;
- (void)setVideoInputDevice:(id)arg1;
- (void)getVideoInputDevices:(CDUnknownBlockType)arg1;
- (void)setOutputDevice:(id)arg1;
- (void)getOutputDevices:(CDUnknownBlockType)arg1;
- (void)setInputDevice:(id)arg1;
- (void)getInputDevices:(CDUnknownBlockType)arg1;
- (void)setEmitVADLevel:(_Bool)arg1:(_Bool)arg2:(id)arg3;
- (void)setOutputVolume:(float)arg1;
- (void)setInputVolume:(float)arg1;
- (void)setTransportOptions:(id)arg1;
- (void)updateIdleTimer;
- (void)updateAudioSession:(_Bool)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)handleOnVideoCallback:(id)arg1;
- (void)handleNoInputCallback:(id)arg1;
- (void)handlePingTimeoutCallback:(id)arg1;
- (void)handlePingCallback:(id)arg1;
- (void)handleDeviceChangedChanged:(id)arg1;
- (void)handleVoiceLevelChanged:(id)arg1;
- (void)handleSpeakingStatusChanged:(id)arg1;
- (id)supportedEvents;
- (void)invalidate;
- (void)clearRenderer:(id)arg1 forStream:(id)arg2;
- (void)setRenderer:(id)arg1 forStream:(id)arg2;
- (void)tryDiscord:(CDUnknownBlockType)arg1 fallback:(CDUnknownBlockType)arg2;
- (void)tryDiscord:(CDUnknownBlockType)arg1;
- (struct Discord *)discord;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
- (id)constantsToExport;
- (id)init;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

